/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vuric_nativemusicsampler_nativeaudio_NativeWrapper */

#ifndef _Included_com_vuric_nativemusicsampler_nativeaudio_NativeWrapper
#define _Included_com_vuric_nativemusicsampler_nativeaudio_NativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vuric_nativemusicsampler_nativeaudio_NativeWrapper
 * Method:    init
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_com_vuric_nativemusicsampler_nativeaudio_NativeWrapper_init
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     com_vuric_nativemusicsampler_nativeaudio_NativeWrapper
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vuric_nativemusicsampler_nativeaudio_NativeWrapper_shutdown
  (JNIEnv *, jclass);

/*
 * Class:     com_vuric_nativemusicsampler_nativeaudio_NativeWrapper
 * Method:    loadSample
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_vuric_nativemusicsampler_nativeaudio_NativeWrapper_loadSample
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_vuric_nativemusicsampler_nativeaudio_NativeWrapper
 * Method:    unloadSample
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_vuric_nativemusicsampler_nativeaudio_NativeWrapper_unloadSample
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_vuric_nativemusicsampler_nativeaudio_NativeWrapper
 * Method:    setPlayState
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_vuric_nativemusicsampler_nativeaudio_NativeWrapper_setPlayState
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_vuric_nativemusicsampler_nativeaudio_NativeWrapper
 * Method:    getPlayState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_vuric_nativemusicsampler_nativeaudio_NativeWrapper_getPlayState
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_vuric_nativemusicsampler_nativeaudio_NativeWrapper
 * Method:    setBandLevels
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_vuric_nativemusicsampler_nativeaudio_NativeWrapper_setBandLevels
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_vuric_nativemusicsampler_nativeaudio_NativeWrapper
 * Method:    getBandLevels
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_vuric_nativemusicsampler_nativeaudio_NativeWrapper_getBandLevels
  (JNIEnv *, jclass);

/*
 * Class:     com_vuric_nativemusicsampler_nativeaudio_NativeWrapper
 * Method:    setLoop
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_vuric_nativemusicsampler_nativeaudio_NativeWrapper_setLoop
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_vuric_nativemusicsampler_nativeaudio_NativeWrapper
 * Method:    isLooping
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_vuric_nativemusicsampler_nativeaudio_NativeWrapper_isLooping
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_vuric_nativemusicsampler_nativeaudio_NativeWrapper
 * Method:    setVolume
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_vuric_nativemusicsampler_nativeaudio_NativeWrapper_setVolume
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_vuric_nativemusicsampler_nativeaudio_NativeWrapper
 * Method:    initLinker
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_vuric_nativemusicsampler_nativeaudio_NativeWrapper_initLinker
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_vuric_nativemusicsampler_nativeaudio_NativeWrapper
 * Method:    linkCallbackFunction
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_vuric_nativemusicsampler_nativeaudio_NativeWrapper_linkCallbackFunction
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
