/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vuric_nativemusicsampler_utils_NativeWrapper */

#ifndef _Included_com_vuric_nativemusicsampler_utils_NativeWrapper
#define _Included_com_vuric_nativemusicsampler_utils_NativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vuric_nativemusicsampler_utils_NativeWrapper
 * Method:    init
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_vuric_nativemusicsampler_utils_NativeWrapper_init
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     com_vuric_nativemusicsampler_utils_NativeWrapper
 * Method:    loadSample
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_vuric_nativemusicsampler_utils_NativeWrapper_loadSample
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_vuric_nativemusicsampler_utils_NativeWrapper
 * Method:    unloadSample
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_vuric_nativemusicsampler_utils_NativeWrapper_unloadSample
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_vuric_nativemusicsampler_utils_NativeWrapper
 * Method:    setPlayState
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_vuric_nativemusicsampler_utils_NativeWrapper_setPlayState
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_vuric_nativemusicsampler_utils_NativeWrapper
 * Method:    getPlayState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_vuric_nativemusicsampler_utils_NativeWrapper_getPlayState
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_vuric_nativemusicsampler_utils_NativeWrapper
 * Method:    setBandLevels
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_vuric_nativemusicsampler_utils_NativeWrapper_setBandLevels
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_vuric_nativemusicsampler_utils_NativeWrapper
 * Method:    getBandLevels
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_vuric_nativemusicsampler_utils_NativeWrapper_getBandLevels
  (JNIEnv *, jobject);

/*
 * Class:     com_vuric_nativemusicsampler_utils_NativeWrapper
 * Method:    setLoop
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_vuric_nativemusicsampler_utils_NativeWrapper_setLoop
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_vuric_nativemusicsampler_utils_NativeWrapper
 * Method:    isLooping
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_vuric_nativemusicsampler_utils_NativeWrapper_isLooping
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
